NAME: 'multi_unet++_b3_DiceLoss.yaml'



DATA:
  NUM_FOLD: 5
  FOLD: 0
  TYPE: "multilabel"
  JSON:
    TRAIN: "data/train/train_mask.json"
    VAL: "data/val/val_mask.json"
  AUGMENT: "albumentations"
#  RANDAUG:
#    N: 2
#    M: 27

  #ALBU:
    #CONFIG: 3
#  IMG_SIZE: (240, 240)
  INP_CHANNEL: 1
#  CROP:
#    ENABLED: True
#    CROPSIZE: (448, 448)

MODEL:
  NAME: "unet++(b3)"
  CLS_HEAD: "linear"
  NUM_CLASSES: 20
  DROPOUT: 0.5

LOSS:
  NAME: "dice"

SOLVER:  
#  OPTIMIZER: "sgd"
  ADAM_EPS: 1e-6
  WARMUP_LENGTH: 5
  GD_STEPS: 1
  SCHEDULER: 'step'
  MIN_LR: 1e-3
  BASE_LR: 1e-3

TRAIN:
  BATCH_SIZE: 8
  EPOCHES: [200]

SYSTEM:
  NUM_WORKERS: 8
  SEED: 27
